name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Download apps
        run: |
          cd download-apps
          npm ci
          npm start
          mv apps/*.apk ..

      - name: Download revanced & patch apps
        run: bash revanced.sh

      - name: Release patched apps
        run: |
          cd revanced
          gh release delete release -y
          git tag -d release
          gh release create release -t "ReVanced Builds" -n "For more information consult the [readme](https://github.com/masterflitzer/revanced#readme)"
          for f in *.apk
          do
            gh release upload release revanced/$file.apk
          done
